version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  assignees:
  - xtermi2
  ignore:
  - dependency-name: org.elasticsearch.client:transport
    versions:
    - 7.11.0
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client
    versions:
    - 7.11.0
  - dependency-name: org.elasticsearch:elasticsearch
    versions:
    - 7.11.0
